### ISSUE TITLE
Data network disconnect 

### ISSUE THREAD

**Issue by airwavesIRE** [MatthewBooth/JFLTE-GPE#19]
The data network will disconnect intermittently only to reconnect a couple of mins later.  It's not a network signal issue as my wife's S4 running stock has not got same issues. 

Baseband I9505XXUGNG8
Latest version of ROM. 

Lobe the ROM though,  great work

**Comment by MatthewBooth** [comment]
This is probably down to the QC-RIL and not the Samsung RIL (use din stock). I noticed this too, usually when swapping between 4G and 3G.

**Comment by airwavesIRE** [comment]
Is there anyway to fix this,  Apologies I have no idea what QC RIL is.

**Comment by MatthewBooth** [comment]
Not really, no. It's how the library is programmed, and honestly, if you're using an i9505 like me, and not a i9505G, it may well be the fact that our modem isn't designed to work with the QC-RIL. The modems we flash on the i9505 are all designed for the Samsung RIL (sec-ril.so)

QC = Qualcomm
RIL = Radio Interface Layer

**Comment by airwavesIRE** [comment]
Thanks for the reply.  Yes I'm on an I9505.
