### ISSUE TITLE
Unresponsive Black Screen while in Call

### ISSUE THREAD

**Issue by CcX85** [MatthewBooth/JFLTE-GPE#27]
While making a call the screen becomes unresponsive and blacks out I have to wait for the other colour to hang up before my phone because Response again. 

Galaxy S4 I9505

**Comment by Mu5tank05** [comment]
I had the same issues in #10, try cleaning out around your proximity sensor with some form of compressed air.

**Comment by rab34207** [comment]
had the same issue had to take mine apart and clean the proximity sensor and the back of the glass where it sits I used a qtip

**Comment by MatthewBooth** [comment]
Yeah this should be the same as #10
