### ISSUE TITLE
"System Update Downloaded"

### ISSUE THREAD

**Issue by GregoryGHarding** [MatthewBooth/JFLTE-GPE#32]
so lollipop went and downloaded 5.1 direct from the OS and is asking me to install.. if i go about this im sure its going to soft brick my phone.. so.. wondering when you will be pushing an update via OTAUpdates?

**Comment by kingofnerds** [comment]
I tried to install the downloaded update,  but my twrp can't seem to find it once the phone boots into recovery.  So I am still on 5.0.1

**Comment by ImNotJayy** [comment]
Same here, i get the notification to install 5.1 but there's not an update to install

**Comment by MatthewBooth** [comment]
It's common knowledge that GPE ROMs for the S4 do not get OTA updates from Google :/ This is not an issue I can fix without doing my OWN update and sending it via my OTA app.

**Comment by GregoryGHarding** [comment]
its exactly what i asked, the os autodownloaded the update, and asked to install. so my question was if you will be pushing 5.1 any time soon now that its out for GPE
