### ISSUE TITLE
WCDMA won't stick

### ISSUE THREAD

**Issue by wtf911** [MatthewBooth/JFLTE-GPE#34]
I'm using an unlocked sprint s4. (both internationally and domestically unlocked) Using the 2015-07-02 5.0.1 build I had no problem switching to WCDMA under cell network settings and using my T-mobile sim card. I just updated to the new 2015-09-19 build and now when I try to select WCDMA it won't stick, it just reverts back to sprint. Any help? :)

**Comment by crysty2k5** [comment]
Same thing on my side.  Thx

**Comment by crysty2k5** [comment]
Actually I believe there is something visual with all switches.  I have background data restricted and the switch for data connection remains all the tine on even if in data usage is all the time off.  If I reboot,  everything goes back to normal fir a period and then again happens.  Thank you!

**Comment by betofoca** [comment]
I'm having the same problem, everytime it switches, keeps alerting! It's annoing
