### ISSUE TITLE
Google Voice does not work with current dialer

### ISSUE THREAD

**Issue by mjdavis871** [MatthewBooth/JFLTE-GPE#5]
Google voice does not dial out with this dialer...you can call from the carrier, but not with GV

**Comment by mjdavis871** [comment]
Google voice doesn't work in current dialer.  Will dial out using carrier number, not not with GV/

**Comment by mjdavis871** [comment]
Has there been any updates to the issue?

**Comment by Kryten2k35** [comment]
Pretty sure Google Voice was replaced by Hangouts late last year. Voice Dialling works great, though, but Google Voice is now Hangouts.

**Comment by mjdavis871** [comment]
That's half right.  Hangouts lets you call using wifi or data.  The dialer uses traditional minutes and uses the Google voice app in conjunction with the dialer to make calls. The dialer in this rom crashes or doesn't call out with Google voice, but the dialer in CM12 will.

**Comment by hotrody2g** [comment]
You are right Mjdavis871, its really annoying. I thought it was GV, but its the dialer. i tried to use a different dialer but i cant even change the default dialer.

**Comment by Kryten2k35** [comment]
The dialer isn't for Google Voice. I'm really confused. But it could also be that Google are dropping GV.

**Comment by hotrody2g** [comment]
I have google voice, when i dial a number using my cell phone dialer, its asks me if i want to use GV or the traditional way. When I pick GV, the dialer crashes, and it doesn't dial out. It would normal just call out with the stock dialer, using my GV number, just like the picture. i understand its not the same dialer but that whats it supposed to do. Another thing little bit off topic the direct dialer widget doesn't work also, it doesn't direct dial. IDK but maybe thats the problem with the dialer. 

![image](https://cloud.githubusercontent.com/assets/11277462/6448662/64befe8e-c0d0-11e4-8d42-c7e63cb8fe70.png)

**Comment by Kryten2k35** [comment]
Well, I don't know anything about GV, but I do know they're putting ti to bed for Hangouts to make way. You should use Hangouts Dialer.

https://play.google.com/store/apps/details?id=com.google.android.apps.hangoutsdialer&hl=en_GB

https://support.google.com/hangouts/answer/6079064?hl=en-GB

**Comment by Kryten2k35** [comment]
Also, a Play Store search for Google Voice doesn't seem to list the app, but Hangouts Dialer is top https://play.google.com/store/search?q=google%20voice&c=apps&hl=en_GB

**Comment by mjdavis871** [comment]
The hangouts dialer only works on WiFi or data...

**Comment by mjdavis871** [comment]
Also, the cm12 dialer works with Google Voice

**Comment by hotrody2g** [comment]
is there a way that the dialer can be change to CM 12 dialer that works with  GV like mjdavis is talking about? Or have the ability to change the default dialer, because hangouts doesn't really work it drop calls most of the time. Hopefully this also solves the direct dialer widget too.

**Comment by mjdavis871** [comment]
An option would be  awesome if possible
